spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  sql:
    init:
      mode: always
server:
  port: 9090
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
security:
  jwt:
    token:
      secret-key: my-secret-key